---
language: objective-c

matrix:
    include:
        - os: osx
          osx_image: xcode8.2

before_install:
    - gem install xcpretty --no-rdoc --no-ri --no-document --quiet
    - gem install cocoapods --no-rdoc --no-ri --no-document --quiet

install:
    - pod repo remove master
    - pod setup
    - pod install

script:
    - set -o pipefail && xcodebuild -workspace Nocilla.xcworkspace -scheme 'Nocilla' -destination 'platform=iOS Simulator,name=iPhone 6,OS=10.1' -sdk iphonesimulator build test CODE_SIGN_IDENTITY=- | xcpretty -c
